### ISSUE TITLE
Ubuntu not supported 

### ISSUE THREAD

**Issue by gdsalim** [uwzis/GPU-Passthrough-Manager#12]
The script couldnt find `mkinicpio.conf` , i believe this is a file that exists only in Arch

**Comment by uwzis** [comment]
That is very true... For now just make sure vfio modules are loaded into initramfs. It should work after that.

**Comment by fr000gs** [comment]
https://unix.stackexchange.com/questions/268903/what-is-the-equivalent-of-mkinitcpio-conf-on-debian

**Comment by uwzis** [comment]
I just added Ubuntu support to the script, I'm not sure if it works since I don't have time to test it.
