### ISSUE TITLE
Support for systemd-boot?

### ISSUE THREAD

**Issue by curiousercreative** [uwzis/GPU-Passthrough-Manager#23]
Some distros (such as Pop!_OS) do not use GRUB for bootloading and instead rely on systemd-boot.

**Comment by uwzis** [comment]
Support for systemd-boot was implemented in pull request #13. What happens when you run the first time setup?

**Comment by curiousercreative** [comment]
> Support for systemd-boot was implemented in pull request #13. What happens when you run the first time setup?

I haven't tried, just read the README that is written for GRUB. Let's make this issue about documentation then?

**Comment by uwzis** [comment]
Sure, I have a new release coming soon.
