### ISSUE TITLE
GPU Passthrough Manager not compatible with certain laptops

### ISSUE THREAD

**Issue by ghost** [uwzis/GPU-Passthrough-Manager#26]
The most recent version of GPU Passthrough Manager (1.2.1) does not run the VFIO scripts successfully on my MSI GS65 Stealth Thin 8RF running pure Arch Linux. I had to reinstall my entire operating system after running this program despite the fact my device meets all of the listed requirements due to my operating system becoming unbootable after first time setup. Please fix.

**Comment by uwzis** [comment]
Skill issue

**Comment by uwzis** [comment]
You bricked your system when you were adding other modules, your grub didn't build correctly. Try again.
