### ISSUE TITLE
Trying to install on Mint, make not cooperating

### ISSUE THREAD

**Issue by stephepush** [uwzis/GPU-Passthrough-Manager#36]
When I run make I initially got the following:

```
  CC	tools/reboot.c
  CXX	GPUPM.cpp
Package jsoncpp was not found in the pkg-config search path.
Perhaps you should add the directory containing `jsoncpp.pc'
to the PKG_CONFIG_PATH environment variable
No package 'jsoncpp' found
In file included from GPUPM.cpp:2:
/usr/include/gtk-3.0/gtk/gtk.h:30:10: fatal error: gdk/gdk.h: No such file or directory
   30 | #include <gdk/gdk.h>
      |          ^~~~~~~~~~~
compilation terminated.
make: *** [Makefile:16: gpupm] Error 1
```

After installing libgtk-3-dev, I tried running again and got back:

```
  CC	tools/reboot.c
  CXX	GPUPM.cpp
Package jsoncpp was not found in the pkg-config search path.
Perhaps you should add the directory containing `jsoncpp.pc'
to the PKG_CONFIG_PATH environment variable
No package 'jsoncpp' found
In file included from GPUPM.cpp:2:
/usr/include/gtk-3.0/gtk/gtk.h:30:10: fatal error: gdk/gdk.h: No such file or directory
   30 | #include <gdk/gdk.h>
      |          ^~~~~~~~~~~
compilation terminated.
make: *** [Makefile:16: gpupm] Error 1

```

I installed jsoncpp, and now when I run make all I get is :

```
  CC	tools/reboot.c
  CXX	GPUPM.cpp
  CC	tools/apphandler.c
```

I'm using Linux Mint 21.1 Cinnamon

**Comment by uwzis** [comment]
You have to get the right version of GTK, I have got it to work on Ubuntu but I forgot what package it is. Try installing all the different ones until you get it to work. When you do let us know what package it is so others can have a better time with it.

**Comment by uwzis** [comment]
I have verified that it compiles with lib32gtk-3-dev. on Ubuntu 22.04.1 using the apt repos. The binary name is GPUPM. Are you sure it isn't compiled?

**Comment by stephepush** [comment]
> I have verified that it compiles with lib32gtk-3-dev. on Ubuntu 22.04.1 using the apt repos. The binary name is GPUPM. Are you sure it isn't compiled?

Thank you for looking into this. It seems that I can't find lib32gtk-3-dev in the apt repos for Mint (though I think they share Ubuntu's repos at some point?). 

I'm new at building things from source, so I'm not sure if this is just compiling somewhere. When I run a search, I'm not getting anything, though.

**Comment by ajgringo619** [comment]
On Mint, the packages should be one of these, although I'm not sure why you need the 32-bit version:
```
$ apt search gtk-3-dev
libgtk-3-dev
libgtk-3-dev:i386
```

**Comment by stephepush** [comment]
> On Mint, the packages should be one of these, although I'm not sure why you need the 32-bit version:
> 
> ```
> $ apt search gtk-3-dev
> libgtk-3-dev
> libgtk-3-dev:i386
> ```

upthread, uwzis says that the code compiles using lib32gtk-3-dev. Doesn't the 32 mean 32bit? I would've though libgtk-3-dev:i386 meant similar, and that also doesn't seem to be working...

**Comment by stephepush** [comment]
I got it to work, it did compile. Thanks for the help.

**Comment by uwzis** [comment]
What fixed the issue?
