### ISSUE TITLE
passthrough manager wont detect intel 12th gen IGPU

### ISSUE THREAD

**Issue by zxq5-dev** [uwzis/GPU-Passthrough-Manager#38]
![image](https://user-images.githubusercontent.com/80643031/214719759-cde4e22f-503e-4ae7-be92-0193af1c9170.png)

it detects my radeon gpu and the audio for both gpus but it doesnt seem to recognise the intel igpu, i've got the latest version of mesa so idk what the problem is

**Comment by uwzis** [comment]
Is the IGPU turned on?

**Comment by uwzis** [comment]
Can you post the output of this command. lspci -k | grep VGA
