### ISSUE TITLE
GPU not loading correct drivers when selecting load VFIO

### ISSUE THREAD

**Issue by Schweeeeeeeeeeeeeeee** [uwzis/GPU-Passthrough-Manager#39]
![image](https://user-images.githubusercontent.com/88291316/233374457-268ed4d1-d852-4f68-b941-2199fc78aa82.png)
I've selected the bottom 2 options to pass through by using VFIO drivers, but only the audio controller is passing through.
I am so sorry if I just clicked the wrong two, but I think I selected the wright ones, and It's still not passing them through.

I'd be good it these IDs (as marked in the picture) would show up in the app, so you can't select the wrong ones.
![image](https://user-images.githubusercontent.com/88291316/233375467-173e544d-645c-4d9a-bfc9-115db0f6d296.png)

I may have loaded VFIO drivers to the wrong GPU because it wasn't named correct (also marked below)
![image](https://user-images.githubusercontent.com/88291316/233376602-75e712a9-1cda-43eb-938c-451f3cfb90f8.png)

**Comment by knxwille** [comment]
aaaa:bbbb,cccc:dddd style device ids doen't work anymore. Someone offered 01:00.1 styel device ids.
I did not made it.  You may try.
PS: Use lspci -nnk to get 01:00.1 style device ids.
