### ISSUE TITLE
Stuck at "Starting dracut pre-udev hook..." after loading vfio (and reboot) - EndeavourOS

### ISSUE THREAD

**Issue by Cappellohack** [uwzis/GPU-Passthrough-Manager#40]
I simply selected the GPU entries and one audio device, clicked on "Load VFIO" and rebooted. Now I'm stuck at:

"Starting dracut pre-udev hook...".

I can boot into Linux if I select "(fallback initramfs)" in grub.

So far I have added "vfio_virtqfd" and "crc32c" in /etc/dracut.conf.d/10-vfio.conf. (Saw that in another issue post).
Created a copy of 10-vfio.conf, named vfio.conf (always in /etc/dracut.conf.d/)
Removed the audio entry in /etc/modprobe.d/vfio.conf.
Rebuild dracut with "sudo dracut-rebuild" and "sudo dracut -f".

I made all this changes while booted in "fallback initramfs", so I don't know how much it affected the "normal" boot.

OS: EndeavourOS

EDIT: Also added "amd_iommu=on rd.driver.pre=vfio-pci" to /etc/default/grub since "GRUB_CMDLINE_LINUX" was empty.
There is also "GRUB_CMDLINE_LINUX_DEFAULT" with a bunch of stuff, but no iommu or vfio entries.

Ran also fts.sh. Didn't help either....

**Comment by uwzis** [comment]
This was added to to Linux kernel in the newer versions, I fixed this bug by removing that module from the first tine setup script because I noticed it wouldn't build intramfs correctly. remove vfio_virtqfd module and it should fix the issue.

**Comment by uwzis** [comment]
it should

**Comment by Cappellohack** [comment]
After running GPUPM again, it got stuck at "Starting dracut pre-udev hook..." again.
/etc/dracut.conf.d/10-vfio.conf and /etc/modprobe.d/vfio.conf were unchanged. So no vfio_virtqfd.

Had to delete both files to boot normally.

**Comment by uwzis** [comment]
does it build correctly with no modules added?

**Comment by nikolaevigor** [comment]
i think i have related issue
got stuck at
```
::runnin early hook [udev]
Starting systemd-udevd version 253.7-1-arch
```
during boot

**Comment by nikolaevigor** [comment]
this [blog post](https://hardcoded.info/post/2023/03/04/pci-passthrough-using-vfio-pci-for-linux-kernel-version-6-solution/) seems related

**Comment by nikolaevigor** [comment]
I've managed to boot by blindfold entering usual commands
